[project]
name = "router-contracts"
type = "tealscript"

[project.deployments]
localnet = { name = "localnet", network = "localnet" }
testnet = { name = "testnet", network = "testnet" }

[project.tealscript]
compiler = "tealscript"
out_dir = "artifacts"

[project.dependencies]
algosdk = "^3.0.0"
"@algorandfoundation/tealscript" = "^0.60.0"

[project.devDependencies]
"@types/jest" = "^29.5.0"
"@types/node" = "^20.0.0"
jest = "^29.5.0"
"ts-jest" = "^29.1.0"
typescript = "^5.3.0"